[tool.poetry]
name = "bdi-aircraft-api"
version = "0.1.0"
description = "Big Data Infrastructure Aircraft API"
authors = ["Natia Utrugashvili <natia.utrugashvili@example.com>"]
readme = "README.md"
packages = [{include = "bdi_api"}]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.115.2"
uvicorn = {extras = ["standard"], version = "^0.34.0"}
requests = "^2.31.0"
pandas = "^2.0.0"
pyarrow = "^14.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"
pytest-cov = "^6.1.1"
ruff = "^0.11.7"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
